export const ROUTES = {
  LOGIN: "/",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  DASHBOARD: "/dashboard",
  NOTIFICATIONS: "/notifications",
  SETTINGS: "/settings",
  ABOUT: "/about",
  HELP: "/help",
  DEVICES: "/farm_control_system/devices",
  DEVICE_PROFILES: "/farm_control_system/device-profiles",
  GRIDSTACK: (id) => `/farm_control_system/devices/gridstack/${id}`,
  HISTORY: (id) => `/farm_control_system/devices/history/${id}`,
  THRESHOLDS: "/farm_control_system/thresholds",
  AUTOMATION_RULES: "/farm_control_system/automation-rules",
  SCHEDULES: "/farm_control_system/schedules",
  FARMS: "/farm_control_system/farms",
  FARM_DETAIL: (id) => `/farm_control_system/farms/${id}`,
  ANALYTICS: "/farm_control_system/analytics",
  // Admin
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_USERS: "/admin/users",
  ADMIN_DEVICES: "/admin/devices",
  ADMIN_SENSORS: "/admin/sensors",
  ADMIN_AUDIT_LOGS: "/admin/audit-logs",
  ADMIN_DEVICE_LOGS: "/admin/device-logs",
  ADMIN_NOTIFICATIONS: "/admin/notifications",
  ADMIN_MENUS: "/admin/menus",
  ADMIN_SETTINGS: "/admin/settings",
};
